const GRAPH_GRID = 15
const RED = '#e60000'
const BLACK = '#000000'
const TARGETMARKER_SIZE = 15
const GAP_SIZE = 2.5
const RADIUS_SIZE = 4
const SNAP_RADIUS = 20
const EDGE_STROKE_WIDTH = 1.5
const PASTE_OFFSET = 32
const STENCIL_NODE_GAP = 50
const STENCIL_GROUP_PADDING = 40
export {
  GRAPH_GRID,
  RED,
  BLACK,
  TARGETMARKER_SIZE,
  GAP_SIZE,
  RADIUS_SIZE,
  SNAP_RADIUS,
  EDGE_STROKE_WIDTH,
  PASTE_OFFSET,
  STENCIL_NODE_GAP,
  STENCIL_GROUP_PADDING,
}
